import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { getUserData } from '../../adapters/user'
import Message from '../../components/chat/Message'
import User from '../../components/chat/user'
import { useRouter } from 'next/router'
import { getCustomerAllConversation } from '../../adapters/chat/conversation'

export default function MessageCenter() {

  const router = useRouter()
  const [conversations, setConversations] = useState([])
  const [messages, setMessages] = useState(null)

  useEffect(()=> {
    const fetcher = async () => {
      try {
        const response = await getUserData()
        if(!response.data){
          router.push('/auth/sign-in')
        }
      } catch (error) {
        
      }
      try {
        const conversationsResponse = await getCustomerAllConversation()
        console.log("conversations : ", conversationsResponse?.data)
        setConversations(conversationsResponse?.data)
      } catch (error) {
        console.log(error?.response)
      }
    }

    fetcher()
  }, [])

  const handleSetMessages = ( messages ) => {
    console.log("messages: ", messages)
    setMessages(messages)
  }
  return (
    <div className='container mx-auto py-8'>
       <Head>
          <title>Balushai Ecommerce - Chat</title>
          <meta name="description" content="Generated by create next app" />
          <link  rel="icon" href="/images/logo.jpg" />
        </Head>
      <div className='grid grid-cols-12 gap-4'>
        <div className='col-span-4 bg-white py-4 rounded-md'>
          <div className='text-center border-b-4 border-[#D23E41] pb-4'>
            <h4 className='text-2xl'>Chat List</h4>
          </div>
          {
            conversations?.map((conversation, index) => {
              return <User key={index} data={conversation} setMessages={handleSetMessages}/>
            })
          }
        </div>
        <div className='col-span-8'>
          <Message messages={messages}/>
        </div>
      </div>
    </div>
  )
}
