export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_TO_CART = 'UPDATE_TO_CART'
export const INCREASE_SINGLE_QUANTITY = 'INCREASE_SINGLE_QUANTITY'
export const DECREASE_SINGLE_QUANTITY = 'DECREASE_SINGLE_QUANTITY'

export const REFRESH_CART =   'REFRESH_CART'