import Head from 'next/head'
import { Provider, useDispatch } from 'react-redux'
import StartingComponent from '../components/StartingComponent'
import Toast from '../components/toast/Toast'
import axios from 'axios'
import { customer } from '../constants'
import Footer from '../layout/footer/Footer'
import Header from '../layout/header/Header'
import store from '../redux/store'
import '../styles/globals.css'
import React from 'react'
import MobileFooter from '../layout/mobile/footer/MobileFooter'
import https from 'https'
axios.defaults.headers.common['Authorization'] = customer || ""
axios.defaults.httpsAgent = new https.Agent({
  rejectUnauthorized: false
})

function MyApp({ Component, pageProps }) {


  // useEffect(()=> {
  //   const fetcher = async() => {
  //     try {
  //       const reponse = await getUserData()
  //       dispatch(setUserData(reponse.data))
  //     } catch (error) {
        
  //     }
  //   }
  // }, [])

  return (
    <div className='relative scroll-smooth'>
     <Head>
      <title>Balushai Ecommerce</title>
      <meta name="description" content="Generated by create next app" />
      <link  rel="icon" href="/images/logo.jpg" />
    </Head>
     <Provider store={store}>
        <Header/>
          <main>
            <Component {...pageProps} />
          </main>
        <Footer/>
        <div className='sm:hidden'>
          <MobileFooter/>
        </div>
        <Toast/>
        {/* <StartingComponent/> */}
     </Provider>
    </div>
  )
}

export default MyApp
