import Head from 'next/head'
import HeroSection from '../components/home/HeroSection'
import MobileBanner from '../components/home/mobile/MobileBanner'
import MobileHeroCategory from '../components/home/mobile/MobileHeroCategory'
import ProductCard from '../components/home/ProductCard'
import ProductSection from '../components/home/ProductSection'
import SuperDealsSection from '../components/home/SuperDealsSection'
import Footer from '../layout/footer/Footer'
import Header from '../layout/header/Header'
import MobileFooter from '../layout/mobile/footer/MobileFooter'
import Link from 'next/link'
import { AllProducts } from '../adapters/product'
import { setUserData } from '../redux'
import { useDispatch } from 'react-redux'
import { getUserData } from '../adapters/user'
import MobileProductSection from '../components/home/mobile/MobileProductSection'
import MobileHeroSlider from '../components/home/mobile/MobileHeroSlider'
import { useEffect, useState } from 'react'

export default function Home({products}) {
  
  // const [products, setProducts] = useState([])

  // useEffect(() => {
  //   const fetcher = async() => {
  //     try {
  //       const productsResponse = await AllProducts()
  //       setProducts(productsResponse?.data)
  //       console.log(productsResponse?.data)
  //     } catch (error) {
  //       console.log("Something went wrong index 30")
  //     }
  //   }

  //   fetcher()
  // }, [])

  return (
    <div>
      <Head>
        <title>Balushai Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="icon" href="/images/logo.jpg" />
      </Head>
      
      <div className='hidden sm:block'>
        <HeroSection/>
        {/* <SuperDealsSection/> */}
        <ProductSection products={products}/>
      </div>

      {/* only visible on mobile device */}
      <div className='sm:hidden'>
        <div className='mb-8'>
          <MobileHeroSlider/>
          <MobileHeroCategory/>
          <MobileBanner/>
          <MobileProductSection products={products}/>
        </div>
      </div>

      
    </div>
  )
}

export async function getServerSideProps(context) {
  const response = await AllProducts()
  // const userInfo = await getUserData()
  // console.log("userInfo: ", userInfo)
  return {
    props: {
      products: response.data
    }, // will be passed to the page component as props
    // revalidate: 10,
  }
}

